version: "3.3"
services:

  twio-python:
    container_name: twio-${ENV}-python
    image: twio-python-server:${TAG}
    build:
      context: ./
      dockerfile: docker-config/python-server.dockerfile
    ports:
      - 8000:8000
    links:
      - db:db
    networks:
      - outside
    logging:
      driver: syslog
    restart: always

  db:
    image: mysql
    container_name: twio-${ENV}-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: doit
      MYSQL_DATABASE: twio
      MYSQL_USER: twio
      MYSQL_PASSWORD: twio
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - outside
    logging:
      driver: syslog
    restart: always

volumes:
  db-volume:
    external:
      name: twio-${ENV}-db

networks:
  outside:
    external:
      name: twio-${ENV}
