version: "3.3"
services:

  twio-python:
    container_name: twio-${ENV}-python
    image: twio-python-server:${TAG}
    build:
      context: ./
      dockerfile: docker-config/python-server.dockerfile
    links:
      - db:db
    volumes:
      - file-volume:/opt/twio_web/media
      - cache-volume:/opt/static
    networks:
      - outside
    logging:
      driver: syslog
    restart: always

  twio-nginx:
    image: twio-nginx-server
    build:
      context: ./
      dockerfile: docker-config/nginx-server.dockerfile
    depends_on:
      - twio-python
    volumes:
      - file-volume:/opt/media
      - cache-volume:/opt/static
    ports:
      - 8000:80
    networks:
      - outside
    logging:
      driver: syslog
    restart: always

  db:
    image: mysql
    container_name: twio-${ENV}-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: doit
      MYSQL_DATABASE: twio
      MYSQL_USER: twio
      MYSQL_PASSWORD: twio
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - outside
    logging:
      driver: syslog
    restart: always

volumes:
  db-volume:
    external:
      name: twio-${ENV}-db
  file-volume:
    external:
      name: twio-${ENV}-file
  cache-volume:
    external:
      name: twio-${ENV}-cache

networks:
  outside:
    external:
      name: twio-${ENV}
